version: "2"

services:
  nginx:
    image: nginx:1.17.10
    restart: "${RESTART_TYPE}"
    volumes:
      - "${APP_DIR}:/var/www/html:ro"
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
    networks:
      - nginx-proxy-network
      - server

  support_nest:
    image: node:18.18.0-alpine
    restart: "${RESTART_TYPE}"
    volumes:
      - "${APP_DIR}:/var/www/html"
    working_dir: /var/www/html
    command: $PROJECT_RUN_COMMAND
    networks:
      - server
      - database

networks:
  server:
  database:
    external:
      name: wowmi-database
  nginx-proxy-network:
    external:
      name: reverseproxy_default
