version: "2"

services:
  nginx:
    image: nginx:1.17.10
    restart: "${RESTART_TYPE}"
    volumes:
      - "${APP_DIR}:/var/www/html:ro"
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
    networks:
      - nginx-proxy-network
      - server

  support_nest:
    image: node:18.18.0-alpine
    restart: "${RESTART_TYPE}"
    volumes:
      - "${APP_DIR}:/var/www/html"
    working_dir: /var/www/html
    command: $PROJECT_RUN_COMMAND
    networks:
      - server
      - database
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - SWAGGER_PREFIX=${SWAGGER_PREFIX}
      - HOST=${HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MEDIA_STORAGE_URL=${MEDIA_STORAGE_URL}
    env_file:
      - ./.env

networks:
  server:
  database:
    external:
      name: wowmi-database
  nginx-proxy-network:
    external:
      name: reverseproxy_default
